#!/bin/bash
# -*- sh-shell: bash; sh-indentation: 8; tab-width: 8; indent-tabs-mode: t; -*-

if (( $# < 1)); then
	echo "usage: clone-salt-org <dir>"
	echo "  <dir>: directory where repos are cloned into"
	exit 1
fi

clone-org salt "$1"
