#!/usr/bin/bash

# The && version==1 guard ensures that no lines before the first version section are printed
script='
# match version section, print update to <latest version>
/^## / {
  version++
  if(version==1)
    {printf "Update to version %s\n", $2 }
  else
    {exit 0}
}
# match change type and format it with leading "-"
/^### / && version==1 {
  printf "- %s\n", $2
}
# match changelog entry (single line) and format it with leading "  *"
/^-/ && version==1 {
  $1=""
  printf "  *%s\n", $0
};
'

changes=$(awk "$script" ./**/CHANGELOG.md)

if [[ -z "$changes" ]]; then
    echo "No new changelog entries, nothing to do."
    exit 1
else
    export VC_REALNAME="Salt Maintainers" VC_MAILADDR="salt-maintainers@suse.de"
    osc vc --message "${changes}"
fi
